// <auto-generated />
using BlazorApp.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230427111138_yesBro")]
    partial class yesBro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Shared.Models.Salarier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fixPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("portablePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<int>("siteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("serviceId");

                    b.HasIndex("siteId");

                    b.ToTable("Salariers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            email = "Lucien_Pierre32@hotmail.fr",
                            first_name = "Victoire",
                            fixPhone = "+33 272941070",
                            last_name = "Prevost",
                            portablePhone = "+33 224650461",
                            serviceId = 1,
                            siteId = 1
                        },
                        new
                        {
                            Id = 2,
                            email = "Bastien28@yahoo.fr",
                            first_name = "Vinciane",
                            fixPhone = "+33 378159094",
                            last_name = "Berger",
                            portablePhone = "+33 768104368",
                            serviceId = 4,
                            siteId = 4
                        },
                        new
                        {
                            Id = 3,
                            email = "Timothee89@yahoo.fr",
                            first_name = "Amalthée",
                            fixPhone = "0302407841",
                            last_name = "Rodriguez",
                            portablePhone = "+33 435117296",
                            serviceId = 6,
                            siteId = 1
                        },
                        new
                        {
                            Id = 4,
                            email = "Clio_Muller@hotmail.fr",
                            first_name = "Scholastique",
                            fixPhone = "+33 759113854",
                            last_name = "Jean",
                            portablePhone = "+33 233788428",
                            serviceId = 5,
                            siteId = 5
                        },
                        new
                        {
                            Id = 5,
                            email = "Auguste94@yahoo.fr",
                            first_name = "Christine",
                            fixPhone = "+33 163606440",
                            last_name = "Adam",
                            portablePhone = "+33 318503647",
                            serviceId = 4,
                            siteId = 5
                        },
                        new
                        {
                            Id = 6,
                            email = "Zephirin.Muller91@yahoo.fr",
                            first_name = "Jason",
                            fixPhone = "0528202154",
                            last_name = "Guillaume",
                            portablePhone = "+33 792212062",
                            serviceId = 6,
                            siteId = 2
                        },
                        new
                        {
                            Id = 7,
                            email = "Stephane_Louis@hotmail.fr",
                            first_name = "Emmelie",
                            fixPhone = "+33 159399200",
                            last_name = "Caron",
                            portablePhone = "+33 282455437",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 8,
                            email = "Abeline36@gmail.com",
                            first_name = "Édouard",
                            fixPhone = "+33 492906916",
                            last_name = "Philippe",
                            portablePhone = "+33 282415461",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 9,
                            email = "Flodoard_Gaillard@hotmail.fr",
                            first_name = "Fortunée",
                            fixPhone = "0631108938",
                            last_name = "Lambert",
                            portablePhone = "0737974090",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 10,
                            email = "Bruno94@hotmail.fr",
                            first_name = "Aleaume",
                            fixPhone = "0714922753",
                            last_name = "Royer",
                            portablePhone = "0576963367",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 11,
                            email = "Camille.Colin@hotmail.fr",
                            first_name = "Andoche",
                            fixPhone = "+33 782029510",
                            last_name = "Chevalier",
                            portablePhone = "0323996219",
                            serviceId = 6,
                            siteId = 5
                        },
                        new
                        {
                            Id = 12,
                            email = "Segolene_Robin@hotmail.fr",
                            first_name = "Pécine",
                            fixPhone = "+33 245574957",
                            last_name = "Olivier",
                            portablePhone = "0258018107",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 13,
                            email = "Isabelle_Robin@yahoo.fr",
                            first_name = "Léonie",
                            fixPhone = "0653940324",
                            last_name = "Duval",
                            portablePhone = "+33 278730587",
                            serviceId = 5,
                            siteId = 2
                        },
                        new
                        {
                            Id = 14,
                            email = "Ascelin20@hotmail.fr",
                            first_name = "Athalie",
                            fixPhone = "+33 163498997",
                            last_name = "Lefevre",
                            portablePhone = "+33 363809211",
                            serviceId = 6,
                            siteId = 1
                        },
                        new
                        {
                            Id = 15,
                            email = "Rosalie.Marchal62@yahoo.fr",
                            first_name = "Girart",
                            fixPhone = "+33 719710432",
                            last_name = "Lopez",
                            portablePhone = "0334926346",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 16,
                            email = "Gustave_Garcia@hotmail.fr",
                            first_name = "Anne",
                            fixPhone = "0783737796",
                            last_name = "Louis",
                            portablePhone = "0402779865",
                            serviceId = 5,
                            siteId = 1
                        },
                        new
                        {
                            Id = 17,
                            email = "Isabeau_Marchal@gmail.com",
                            first_name = "Séraphin",
                            fixPhone = "0409463578",
                            last_name = "Fabre",
                            portablePhone = "+33 361290684",
                            serviceId = 6,
                            siteId = 2
                        },
                        new
                        {
                            Id = 18,
                            email = "Armance33@hotmail.fr",
                            first_name = "Gustavine",
                            fixPhone = "+33 325989845",
                            last_name = "Philippe",
                            portablePhone = "+33 798046741",
                            serviceId = 5,
                            siteId = 5
                        },
                        new
                        {
                            Id = 19,
                            email = "Titien.Benoit45@yahoo.fr",
                            first_name = "Denise",
                            fixPhone = "0265225185",
                            last_name = "Olivier",
                            portablePhone = "+33 396326188",
                            serviceId = 3,
                            siteId = 2
                        },
                        new
                        {
                            Id = 20,
                            email = "Eliane98@gmail.com",
                            first_name = "Balthazar",
                            fixPhone = "0120993470",
                            last_name = "Riviere",
                            portablePhone = "+33 664982874",
                            serviceId = 4,
                            siteId = 4
                        },
                        new
                        {
                            Id = 21,
                            email = "Elie53@hotmail.fr",
                            first_name = "Cléry",
                            fixPhone = "0778549945",
                            last_name = "Garcia",
                            portablePhone = "0452258232",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 22,
                            email = "Edith_Laine@yahoo.fr",
                            first_name = "Richard",
                            fixPhone = "+33 744490632",
                            last_name = "Perez",
                            portablePhone = "0223910259",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 23,
                            email = "Constant_Lucas@gmail.com",
                            first_name = "Baudouin",
                            fixPhone = "0758883124",
                            last_name = "Pierre",
                            portablePhone = "+33 434134134",
                            serviceId = 6,
                            siteId = 5
                        },
                        new
                        {
                            Id = 24,
                            email = "Astride.Leroux@yahoo.fr",
                            first_name = "Didier",
                            fixPhone = "0621069437",
                            last_name = "Colin",
                            portablePhone = "0262189885",
                            serviceId = 6,
                            siteId = 4
                        },
                        new
                        {
                            Id = 25,
                            email = "Thibault17@hotmail.fr",
                            first_name = "Azalée",
                            fixPhone = "+33 249323843",
                            last_name = "Lopez",
                            portablePhone = "+33 258618884",
                            serviceId = 3,
                            siteId = 3
                        },
                        new
                        {
                            Id = 26,
                            email = "Samuel.Leclercq69@yahoo.fr",
                            first_name = "Céline",
                            fixPhone = "0356740384",
                            last_name = "Lemaire",
                            portablePhone = "+33 579137508",
                            serviceId = 1,
                            siteId = 3
                        },
                        new
                        {
                            Id = 27,
                            email = "Fabrice.Adam@yahoo.fr",
                            first_name = "Alcyone",
                            fixPhone = "+33 666303789",
                            last_name = "Picard",
                            portablePhone = "0469410832",
                            serviceId = 1,
                            siteId = 3
                        },
                        new
                        {
                            Id = 28,
                            email = "Amaliane87@gmail.com",
                            first_name = "Philémon",
                            fixPhone = "+33 473002120",
                            last_name = "Paris",
                            portablePhone = "0164551752",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 29,
                            email = "Lambert.Sanchez@hotmail.fr",
                            first_name = "Carine",
                            fixPhone = "+33 501392777",
                            last_name = "Arnaud",
                            portablePhone = "0382452057",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 30,
                            email = "Jonathan.Baron22@gmail.com",
                            first_name = "Francisque",
                            fixPhone = "+33 413533719",
                            last_name = "Julien",
                            portablePhone = "0408814555",
                            serviceId = 5,
                            siteId = 4
                        },
                        new
                        {
                            Id = 31,
                            email = "Benedicte.Julien@yahoo.fr",
                            first_name = "Céleste",
                            fixPhone = "0193032138",
                            last_name = "Fournier",
                            portablePhone = "0127255871",
                            serviceId = 1,
                            siteId = 3
                        },
                        new
                        {
                            Id = 32,
                            email = "Cecile93@yahoo.fr",
                            first_name = "Octave",
                            fixPhone = "+33 102953486",
                            last_name = "Royer",
                            portablePhone = "+33 725057485",
                            serviceId = 6,
                            siteId = 4
                        },
                        new
                        {
                            Id = 33,
                            email = "Berard.Mercier@yahoo.fr",
                            first_name = "Lucille",
                            fixPhone = "0490026055",
                            last_name = "Fabre",
                            portablePhone = "+33 650311892",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 34,
                            email = "Oury_Perrin38@hotmail.fr",
                            first_name = "Raoul",
                            fixPhone = "+33 467328805",
                            last_name = "Olivier",
                            portablePhone = "0122382657",
                            serviceId = 1,
                            siteId = 5
                        },
                        new
                        {
                            Id = 35,
                            email = "Valentine.Dubois@hotmail.fr",
                            first_name = "Léa",
                            fixPhone = "0612323513",
                            last_name = "Da silva",
                            portablePhone = "0796199981",
                            serviceId = 1,
                            siteId = 1
                        },
                        new
                        {
                            Id = 36,
                            email = "Iseult3@yahoo.fr",
                            first_name = "Marceau",
                            fixPhone = "+33 562316891",
                            last_name = "Meunier",
                            portablePhone = "0544774605",
                            serviceId = 1,
                            siteId = 1
                        },
                        new
                        {
                            Id = 37,
                            email = "Brigitte.Marchand@hotmail.fr",
                            first_name = "Vincent",
                            fixPhone = "0632030213",
                            last_name = "Riviere",
                            portablePhone = "0326631931",
                            serviceId = 4,
                            siteId = 3
                        },
                        new
                        {
                            Id = 38,
                            email = "Emeric_Martin@yahoo.fr",
                            first_name = "Timoléon",
                            fixPhone = "0681231101",
                            last_name = "Gaillard",
                            portablePhone = "+33 111468402",
                            serviceId = 2,
                            siteId = 3
                        },
                        new
                        {
                            Id = 39,
                            email = "Christelle92@hotmail.fr",
                            first_name = "Blaise",
                            fixPhone = "+33 447698669",
                            last_name = "Clement",
                            portablePhone = "0415695347",
                            serviceId = 4,
                            siteId = 1
                        },
                        new
                        {
                            Id = 40,
                            email = "Briac_Jacquet79@yahoo.fr",
                            first_name = "Célestine",
                            fixPhone = "+33 158808761",
                            last_name = "Marie",
                            portablePhone = "0616275557",
                            serviceId = 4,
                            siteId = 4
                        },
                        new
                        {
                            Id = 41,
                            email = "Isidore.Dubois13@hotmail.fr",
                            first_name = "Audrey",
                            fixPhone = "0775475504",
                            last_name = "Renaud",
                            portablePhone = "+33 776543857",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 42,
                            email = "Agrippin98@gmail.com",
                            first_name = "Adelin",
                            fixPhone = "0661037704",
                            last_name = "Leclercq",
                            portablePhone = "+33 714350202",
                            serviceId = 3,
                            siteId = 2
                        },
                        new
                        {
                            Id = 43,
                            email = "Emile38@hotmail.fr",
                            first_name = "Dorian",
                            fixPhone = "0333458889",
                            last_name = "Roger",
                            portablePhone = "+33 760645839",
                            serviceId = 6,
                            siteId = 5
                        },
                        new
                        {
                            Id = 44,
                            email = "Clement.Denis11@yahoo.fr",
                            first_name = "Abelin",
                            fixPhone = "0531922330",
                            last_name = "Roux",
                            portablePhone = "+33 367829540",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 45,
                            email = "Reybaud.Nguyen@gmail.com",
                            first_name = "Anémone",
                            fixPhone = "+33 789547626",
                            last_name = "Leclerc",
                            portablePhone = "+33 366006181",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 46,
                            email = "Tristan_Fernandez44@hotmail.fr",
                            first_name = "Annonciade",
                            fixPhone = "0391040399",
                            last_name = "Rodriguez",
                            portablePhone = "0650171660",
                            serviceId = 3,
                            siteId = 4
                        },
                        new
                        {
                            Id = 47,
                            email = "Maurice_Fournier@yahoo.fr",
                            first_name = "Childebert",
                            fixPhone = "0290249386",
                            last_name = "Breton",
                            portablePhone = "0465188357",
                            serviceId = 1,
                            siteId = 5
                        },
                        new
                        {
                            Id = 48,
                            email = "Emmanuel.Olivier22@yahoo.fr",
                            first_name = "Célien",
                            fixPhone = "0622072308",
                            last_name = "Denis",
                            portablePhone = "0280263402",
                            serviceId = 4,
                            siteId = 2
                        },
                        new
                        {
                            Id = 49,
                            email = "Ancelin.Sanchez45@gmail.com",
                            first_name = "Oury",
                            fixPhone = "0743643147",
                            last_name = "Martin",
                            portablePhone = "+33 291686825",
                            serviceId = 5,
                            siteId = 1
                        },
                        new
                        {
                            Id = 50,
                            email = "Lucienne_Morel25@gmail.com",
                            first_name = "Aude",
                            fixPhone = "+33 648792989",
                            last_name = "David",
                            portablePhone = "0253973286",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 51,
                            email = "Trajan_Collet44@hotmail.fr",
                            first_name = "Annette",
                            fixPhone = "+33 206860851",
                            last_name = "Renault",
                            portablePhone = "+33 332133748",
                            serviceId = 1,
                            siteId = 4
                        },
                        new
                        {
                            Id = 52,
                            email = "Mallaury12@hotmail.fr",
                            first_name = "Jocelyn",
                            fixPhone = "0497393037",
                            last_name = "Carpentier",
                            portablePhone = "0398025235",
                            serviceId = 1,
                            siteId = 3
                        },
                        new
                        {
                            Id = 53,
                            email = "Guerin.Marchal@gmail.com",
                            first_name = "Andéol",
                            fixPhone = "+33 273973551",
                            last_name = "Roy",
                            portablePhone = "0692376929",
                            serviceId = 5,
                            siteId = 3
                        },
                        new
                        {
                            Id = 54,
                            email = "Honore.Renard@hotmail.fr",
                            first_name = "Corentin",
                            fixPhone = "0228041138",
                            last_name = "Joly",
                            portablePhone = "0690570809",
                            serviceId = 6,
                            siteId = 2
                        },
                        new
                        {
                            Id = 55,
                            email = "Violette46@gmail.com",
                            first_name = "Émérencie",
                            fixPhone = "+33 225575591",
                            last_name = "Dupont",
                            portablePhone = "0616324628",
                            serviceId = 2,
                            siteId = 2
                        },
                        new
                        {
                            Id = 56,
                            email = "Penelope57@gmail.com",
                            first_name = "Clarence",
                            fixPhone = "+33 593919368",
                            last_name = "Dufour",
                            portablePhone = "+33 473977651",
                            serviceId = 2,
                            siteId = 1
                        },
                        new
                        {
                            Id = 57,
                            email = "Aglae4@hotmail.fr",
                            first_name = "Aldric",
                            fixPhone = "0719427966",
                            last_name = "Roche",
                            portablePhone = "0101123968",
                            serviceId = 2,
                            siteId = 3
                        },
                        new
                        {
                            Id = 58,
                            email = "Constant.Brunet42@gmail.com",
                            first_name = "Macaire",
                            fixPhone = "+33 105203052",
                            last_name = "Joly",
                            portablePhone = "0186583276",
                            serviceId = 5,
                            siteId = 4
                        },
                        new
                        {
                            Id = 59,
                            email = "Apollinaire_Fleury@gmail.com",
                            first_name = "Rachel",
                            fixPhone = "+33 797749542",
                            last_name = "Barre",
                            portablePhone = "0101896279",
                            serviceId = 3,
                            siteId = 5
                        },
                        new
                        {
                            Id = 60,
                            email = "Caroline_Dumont@gmail.com",
                            first_name = "Conception",
                            fixPhone = "0118514982",
                            last_name = "Giraud",
                            portablePhone = "+33 631154559",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 61,
                            email = "Alexandrine29@gmail.com",
                            first_name = "Fulbert",
                            fixPhone = "0677759751",
                            last_name = "Dupuis",
                            portablePhone = "+33 514059833",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 62,
                            email = "Absalon_Royer48@hotmail.fr",
                            first_name = "Alpinien",
                            fixPhone = "+33 464266584",
                            last_name = "Leclercq",
                            portablePhone = "+33 116748033",
                            serviceId = 3,
                            siteId = 2
                        },
                        new
                        {
                            Id = 63,
                            email = "Thierry_Gerard86@hotmail.fr",
                            first_name = "Camille",
                            fixPhone = "0239819684",
                            last_name = "Blanchard",
                            portablePhone = "+33 552875022",
                            serviceId = 3,
                            siteId = 1
                        },
                        new
                        {
                            Id = 64,
                            email = "Laurent_Barre@yahoo.fr",
                            first_name = "Célien",
                            fixPhone = "0135029722",
                            last_name = "Lefebvre",
                            portablePhone = "0387896383",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 65,
                            email = "Arnaud_Garcia49@yahoo.fr",
                            first_name = "Laurent",
                            fixPhone = "0729751136",
                            last_name = "Morin",
                            portablePhone = "+33 633052893",
                            serviceId = 1,
                            siteId = 4
                        },
                        new
                        {
                            Id = 66,
                            email = "Adhemar.Dufour43@hotmail.fr",
                            first_name = "Nathanaël",
                            fixPhone = "0256808321",
                            last_name = "Renard",
                            portablePhone = "0241336972",
                            serviceId = 1,
                            siteId = 4
                        },
                        new
                        {
                            Id = 67,
                            email = "Alliaume.Roy37@gmail.com",
                            first_name = "Abélard",
                            fixPhone = "+33 707300801",
                            last_name = "Renaud",
                            portablePhone = "0524529241",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 68,
                            email = "Agapet62@gmail.com",
                            first_name = "Georgette",
                            fixPhone = "+33 762277370",
                            last_name = "Da silva",
                            portablePhone = "0669968747",
                            serviceId = 6,
                            siteId = 1
                        },
                        new
                        {
                            Id = 69,
                            email = "Gabin_Fleury9@hotmail.fr",
                            first_name = "Anastase",
                            fixPhone = "+33 459493979",
                            last_name = "Thomas",
                            portablePhone = "0187190164",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 70,
                            email = "Suzon.Michel@gmail.com",
                            first_name = "Cécile",
                            fixPhone = "0577122831",
                            last_name = "Rodriguez",
                            portablePhone = "+33 467480596",
                            serviceId = 4,
                            siteId = 4
                        },
                        new
                        {
                            Id = 71,
                            email = "Didier_Bonnet@gmail.com",
                            first_name = "Gabrielle",
                            fixPhone = "0151392065",
                            last_name = "Garcia",
                            portablePhone = "0588313621",
                            serviceId = 4,
                            siteId = 3
                        },
                        new
                        {
                            Id = 72,
                            email = "Elie_Paul32@hotmail.fr",
                            first_name = "Maxence",
                            fixPhone = "+33 239052768",
                            last_name = "Adam",
                            portablePhone = "0426834012",
                            serviceId = 3,
                            siteId = 4
                        },
                        new
                        {
                            Id = 73,
                            email = "Artheme12@hotmail.fr",
                            first_name = "Raymond",
                            fixPhone = "+33 473705043",
                            last_name = "Simon",
                            portablePhone = "+33 219679098",
                            serviceId = 6,
                            siteId = 2
                        },
                        new
                        {
                            Id = 74,
                            email = "Helier61@hotmail.fr",
                            first_name = "Juste",
                            fixPhone = "+33 301497384",
                            last_name = "Sanchez",
                            portablePhone = "0385742951",
                            serviceId = 6,
                            siteId = 3
                        },
                        new
                        {
                            Id = 75,
                            email = "Gilles.Schneider63@gmail.com",
                            first_name = "Gilbert",
                            fixPhone = "0517356991",
                            last_name = "Boyer",
                            portablePhone = "0726710848",
                            serviceId = 3,
                            siteId = 2
                        },
                        new
                        {
                            Id = 76,
                            email = "Zoe35@hotmail.fr",
                            first_name = "Nicéphore",
                            fixPhone = "+33 155226683",
                            last_name = "Nguyen",
                            portablePhone = "0520181746",
                            serviceId = 5,
                            siteId = 4
                        },
                        new
                        {
                            Id = 77,
                            email = "Rodrigue.Caron@gmail.com",
                            first_name = "Fabien",
                            fixPhone = "0238350871",
                            last_name = "Morel",
                            portablePhone = "0153450974",
                            serviceId = 5,
                            siteId = 4
                        },
                        new
                        {
                            Id = 78,
                            email = "Henri69@gmail.com",
                            first_name = "Philippe",
                            fixPhone = "0372213986",
                            last_name = "Guerin",
                            portablePhone = "0115685581",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 79,
                            email = "Wandrille_Maillard4@yahoo.fr",
                            first_name = "Maurice",
                            fixPhone = "0285971440",
                            last_name = "Vidal",
                            portablePhone = "0574849359",
                            serviceId = 2,
                            siteId = 3
                        },
                        new
                        {
                            Id = 80,
                            email = "Fantin57@hotmail.fr",
                            first_name = "Laurane",
                            fixPhone = "0474983188",
                            last_name = "Huet",
                            portablePhone = "+33 274051937",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 81,
                            email = "Rachel_Vincent@hotmail.fr",
                            first_name = "Martial",
                            fixPhone = "0526301584",
                            last_name = "Berger",
                            portablePhone = "+33 361735590",
                            serviceId = 3,
                            siteId = 2
                        },
                        new
                        {
                            Id = 82,
                            email = "Delphin.Noel@yahoo.fr",
                            first_name = "Germaine",
                            fixPhone = "0117012158",
                            last_name = "Sanchez",
                            portablePhone = "0232804607",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 83,
                            email = "Beuve.Baron39@hotmail.fr",
                            first_name = "Jeanne",
                            fixPhone = "0789956290",
                            last_name = "Duval",
                            portablePhone = "0465915253",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 84,
                            email = "Patrice_Laurent18@hotmail.fr",
                            first_name = "Viviane",
                            fixPhone = "+33 382803197",
                            last_name = "Brun",
                            portablePhone = "+33 120312170",
                            serviceId = 4,
                            siteId = 5
                        },
                        new
                        {
                            Id = 85,
                            email = "Joseph72@hotmail.fr",
                            first_name = "Paulette",
                            fixPhone = "+33 626158576",
                            last_name = "Robert",
                            portablePhone = "0173680461",
                            serviceId = 5,
                            siteId = 4
                        },
                        new
                        {
                            Id = 86,
                            email = "Azeline19@gmail.com",
                            first_name = "Nicole",
                            fixPhone = "0697381842",
                            last_name = "Fontaine",
                            portablePhone = "0497893381",
                            serviceId = 4,
                            siteId = 2
                        },
                        new
                        {
                            Id = 87,
                            email = "Elzear.Arnaud35@yahoo.fr",
                            first_name = "Gilbert",
                            fixPhone = "0536710708",
                            last_name = "Julien",
                            portablePhone = "0305183856",
                            serviceId = 6,
                            siteId = 1
                        },
                        new
                        {
                            Id = 88,
                            email = "Bruno_Denis62@yahoo.fr",
                            first_name = "Lothaire",
                            fixPhone = "0258388448",
                            last_name = "Fabre",
                            portablePhone = "0536329195",
                            serviceId = 6,
                            siteId = 2
                        },
                        new
                        {
                            Id = 89,
                            email = "Aimee.Dupont@hotmail.fr",
                            first_name = "Alcime",
                            fixPhone = "0533326522",
                            last_name = "Paris",
                            portablePhone = "+33 333588441",
                            serviceId = 2,
                            siteId = 5
                        },
                        new
                        {
                            Id = 90,
                            email = "Adalric95@gmail.com",
                            first_name = "Marine",
                            fixPhone = "+33 597642331",
                            last_name = "Renard",
                            portablePhone = "+33 237471272",
                            serviceId = 6,
                            siteId = 1
                        },
                        new
                        {
                            Id = 91,
                            email = "Adelie65@yahoo.fr",
                            first_name = "Gabin",
                            fixPhone = "0599068266",
                            last_name = "Marchal",
                            portablePhone = "+33 326065535",
                            serviceId = 2,
                            siteId = 4
                        },
                        new
                        {
                            Id = 92,
                            email = "Philemon.Bertrand54@gmail.com",
                            first_name = "Jules",
                            fixPhone = "0375814281",
                            last_name = "Marchal",
                            portablePhone = "+33 270892770",
                            serviceId = 1,
                            siteId = 3
                        },
                        new
                        {
                            Id = 93,
                            email = "Michael.Baron@yahoo.fr",
                            first_name = "Gontran",
                            fixPhone = "+33 498687978",
                            last_name = "Prevost",
                            portablePhone = "0340377375",
                            serviceId = 5,
                            siteId = 2
                        },
                        new
                        {
                            Id = 94,
                            email = "Rosalie.Brunet@yahoo.fr",
                            first_name = "Séverin",
                            fixPhone = "0425344465",
                            last_name = "Leroux",
                            portablePhone = "0614668153",
                            serviceId = 3,
                            siteId = 3
                        },
                        new
                        {
                            Id = 95,
                            email = "Germain_Philippe25@hotmail.fr",
                            first_name = "Alberte",
                            fixPhone = "0490747926",
                            last_name = "Leroy",
                            portablePhone = "+33 191890387",
                            serviceId = 4,
                            siteId = 3
                        },
                        new
                        {
                            Id = 96,
                            email = "Clara.Dumont88@hotmail.fr",
                            first_name = "Melchior",
                            fixPhone = "+33 799670848",
                            last_name = "Adam",
                            portablePhone = "0771455524",
                            serviceId = 5,
                            siteId = 5
                        },
                        new
                        {
                            Id = 97,
                            email = "Lorraine.Boyer@gmail.com",
                            first_name = "Tonnin",
                            fixPhone = "+33 322962703",
                            last_name = "Duval",
                            portablePhone = "0213617970",
                            serviceId = 4,
                            siteId = 2
                        },
                        new
                        {
                            Id = 98,
                            email = "Gerbert23@hotmail.fr",
                            first_name = "Mathilde",
                            fixPhone = "+33 313104214",
                            last_name = "Pierre",
                            portablePhone = "+33 711945875",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 99,
                            email = "Trajan.Boyer60@gmail.com",
                            first_name = "Hélène",
                            fixPhone = "+33 724239100",
                            last_name = "Marchand",
                            portablePhone = "0556468847",
                            serviceId = 1,
                            siteId = 2
                        },
                        new
                        {
                            Id = 100,
                            email = "Naudet.Fabre@yahoo.fr",
                            first_name = "Angélique",
                            fixPhone = "0682792021",
                            last_name = "Barbier",
                            portablePhone = "0455629553",
                            serviceId = 4,
                            siteId = 5
                        });
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ressources humaines"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Informatique"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comptabilité"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Production"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accueil"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Commercial"
                        });
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Site", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lille"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nantes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nice"
                        });
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Salarier", b =>
                {
                    b.HasOne("BlazorApp.Shared.Models.Service", "service")
                        .WithMany("Salariers")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.Shared.Models.Site", "site")
                        .WithMany("Salariers")
                        .HasForeignKey("siteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");

                    b.Navigation("site");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Service", b =>
                {
                    b.Navigation("Salariers");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Site", b =>
                {
                    b.Navigation("Salariers");
                });
#pragma warning restore 612, 618
        }
    }
}
